-- Insert Executive-Level Compliance Workflows lessons focused on Board Reporting and Strategic Planning
INSERT INTO public.lessons (title, description, category, difficulty, duration_minutes, content, scenario_text, is_published, order_index) VALUES
('Board-Level Compliance Reporting', 'Master the art of communicating compliance status, risks, and strategy to board members effectively.', 'compliance_workflows', 'advanced', 5, '{"sections": [{"title": "Board Communication Essentials", "bullets": ["Focus on material risks and strategic implications", "Use clear metrics and trend analysis", "Provide context and business impact", "Balance transparency with actionable insights"], "content": "Boards need compliance information that enables informed governance decisions."}, {"title": "Reporting Framework", "bullets": ["Executive summary with key takeaways", "Risk heat maps and trend indicators", "Regulatory changes impacting strategy", "Resource needs and recommendations"], "content": "Structured reporting ensures boards receive critical information efficiently."}]}', 'The board requests a compliance briefing for their next meeting. How do you structure a report that demonstrates value while addressing concerns?', true, 44),

('Strategic Compliance Planning', 'Develop multi-year compliance strategies that anticipate regulatory evolution and support business objectives.', 'compliance_workflows', 'advanced', 5, '{"sections": [{"title": "Strategic Assessment", "bullets": ["Analyze regulatory trends and emerging requirements", "Align compliance with business strategy", "Assess competitive compliance positioning", "Identify strategic compliance advantages"], "content": "Strategic compliance transforms obligation into competitive advantage."}, {"title": "Long-term Planning", "bullets": ["Develop 3-5 year compliance roadmap", "Plan for regulatory scenarios", "Build organizational capability", "Integrate with enterprise risk management"], "content": "Proactive planning positions organizations ahead of compliance requirements."}]}', 'Your industry faces significant regulatory change over the next 3 years. How do you develop a strategic compliance plan that supports growth?', true, 45),

('Compliance Program Maturity Assessment', 'Evaluate and advance compliance program maturity to meet evolving organizational and regulatory expectations.', 'compliance_workflows', 'advanced', 5, '{"sections": [{"title": "Maturity Models", "bullets": ["Initial: Ad hoc and reactive", "Developing: Documented but inconsistent", "Defined: Standardized and repeatable", "Optimized: Integrated and continuously improving"], "content": "Understanding maturity enables targeted improvement investments."}, {"title": "Advancement Strategy", "bullets": ["Assess current state against model", "Identify high-impact gaps", "Prioritize improvements by value", "Measure progress with KPIs"], "content": "Systematic maturity advancement demonstrates program effectiveness."}]}', 'An external assessment rates your compliance program as developing rather than defined. How do you advance maturity?', true, 46),

('Compliance Crisis Leadership', 'Lead effectively through major compliance crises while protecting the organization and maintaining stakeholder trust.', 'compliance_workflows', 'advanced', 5, '{"sections": [{"title": "Crisis Response Leadership", "bullets": ["Establish crisis command structure", "Make rapid decisions with incomplete information", "Coordinate across legal, communications, operations", "Balance transparency with legal protection"], "content": "Executive leadership during crises determines organizational outcomes."}, {"title": "Recovery and Prevention", "bullets": ["Conduct thorough root cause analysis", "Implement systemic improvements", "Rebuild stakeholder confidence", "Transform crisis into cultural change"], "content": "How you emerge from crisis defines future resilience."}]}', 'A major compliance violation has been discovered and regulators have been notified. As the executive sponsor, how do you lead the response?', true, 47),

('Compliance Investment and Resource Strategy', 'Make strategic decisions about compliance investments that balance risk mitigation with business enablement.', 'compliance_workflows', 'advanced', 5, '{"sections": [{"title": "Investment Framework", "bullets": ["Quantify compliance costs and benefits", "Prioritize by risk reduction and efficiency", "Consider technology and automation", "Build business case for investments"], "content": "Strategic resource allocation optimizes compliance effectiveness and efficiency."}, {"title": "Resource Optimization", "bullets": ["Right-size compliance team structure", "Leverage technology for scale", "Outsource tactical work strategically", "Invest in high-value expertise"], "content": "Efficient resource allocation delivers more compliance value per dollar."}]}', 'Budget pressures require justifying compliance investments while maintaining effectiveness. How do you prioritize and defend resources?', true, 48),

('Integrating Compliance with Business Strategy', 'Embed compliance considerations into strategic planning and decision-making processes.', 'compliance_workflows', 'advanced', 5, '{"sections": [{"title": "Strategic Integration", "bullets": ["Include compliance in strategic planning", "Assess compliance implications of initiatives", "Position compliance as enabler not blocker", "Create compliance-aware culture"], "content": "Integration ensures compliance supports rather than impedes business objectives."}, {"title": "Value Creation", "bullets": ["Identify compliance as competitive advantage", "Leverage compliance for market differentiation", "Build trust through compliance excellence", "Enable business through proactive compliance"], "content": "Strategic compliance creates business value beyond risk mitigation."}]}', 'The business wants to enter a heavily regulated market. How do you ensure compliance is integrated into the market entry strategy?', true, 49),

('Board Compliance Committee Effectiveness', 'Optimize board compliance committee structure and operations for maximum governance value.', 'compliance_workflows', 'advanced', 5, '{"sections": [{"title": "Committee Structure", "bullets": ["Define charter and responsibilities", "Ensure appropriate expertise and independence", "Establish meeting cadence and agendas", "Clarify escalation and decision rights"], "content": "Well-structured committees provide effective compliance oversight."}, {"title": "Committee Effectiveness", "bullets": ["Focus on strategic and material issues", "Enable deep dives on key risks", "Balance oversight with management support", "Measure and improve committee performance"], "content": "Effective committees strengthen governance without micromanaging."}]}', 'Your board compliance committee is too focused on minutiae and missing strategic risks. How do you improve effectiveness?', true, 50);

-- Insert quiz questions for Board-Level Compliance Reporting
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Board-Level Compliance Reporting'), 'What should board compliance reports prioritize?', '["Detailed policy documentation", "Material risks and strategic implications", "All compliance activities", "Technical compliance metrics"]', 1, 'Boards need to focus on material risks and strategic implications rather than operational details to make informed governance decisions.', 1),
((SELECT id FROM lessons WHERE title = 'Board-Level Compliance Reporting'), 'How should compliance trends be presented to the board?', '["Raw data tables", "Heat maps and visual indicators with context", "Lengthy written reports", "Verbal summaries only"]', 1, 'Visual indicators like heat maps combined with business context enable boards to quickly understand compliance status and trends.', 2);

-- Insert quiz questions for Strategic Compliance Planning
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Strategic Compliance Planning'), 'What timeframe should strategic compliance planning cover?', '["Next quarter only", "3-5 years aligned with business strategy", "Current regulatory requirements only", "Until next audit"]', 1, 'Strategic compliance planning should align with business strategy horizons, typically 3-5 years, to anticipate and prepare for regulatory evolution.', 1),
((SELECT id FROM lessons WHERE title = 'Strategic Compliance Planning'), 'How can compliance provide competitive advantage?', '["By being minimally compliant", "By enabling trusted operations and market differentiation", "By avoiding all regulations", "By copying competitors"]', 1, 'Excellence in compliance can differentiate organizations, build stakeholder trust, and enable business opportunities in regulated markets.', 2);

-- Insert quiz questions for Compliance Program Maturity Assessment
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Compliance Program Maturity Assessment'), 'What characterizes an optimized compliance program?', '["Documented policies", "Ad hoc responses", "Integrated and continuously improving", "Outsourced completely"]', 2, 'Optimized programs are integrated across the organization and continuously improve through systematic measurement and refinement.', 1),
((SELECT id FROM lessons WHERE title = 'Compliance Program Maturity Assessment'), 'How should compliance maturity improvements be prioritized?', '["By regulatory mandate", "By high-impact gaps and business value", "By ease of implementation", "By budget availability"]', 1, 'Prioritizing high-impact gaps that deliver business value ensures maturity investments produce meaningful risk reduction and efficiency.', 2);

-- Insert quiz questions for Compliance Crisis Leadership
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Compliance Crisis Leadership'), 'What is the first leadership priority in a compliance crisis?', '["Assign blame", "Establish crisis command and coordinate response", "Prepare public statement", "Consult with insurers"]', 1, 'Establishing clear crisis command structure and coordinating response across functions is essential for effective crisis management.', 1),
((SELECT id FROM lessons WHERE title = 'Compliance Crisis Leadership'), 'How should leaders approach post-crisis improvement?', '["Move on quickly", "Conduct root cause analysis and implement systemic changes", "Blame individuals", "Wait for regulatory guidance"]', 1, 'Thorough root cause analysis and systemic improvements transform crises into opportunities for strengthening organizational resilience.', 2);

-- Insert quiz questions for Compliance Investment and Resource Strategy
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Compliance Investment and Resource Strategy'), 'How should compliance investments be justified?', '["As pure cost center", "By quantifying risk reduction and business enablement", "By regulatory requirement alone", "By competitor spending"]', 1, 'Quantifying both risk reduction and business enablement value creates compelling business cases for compliance investments.', 1),
((SELECT id FROM lessons WHERE title = 'Compliance Investment and Resource Strategy'), 'What drives efficient compliance resource allocation?', '["Equal distribution across all areas", "Risk-based prioritization and technology leverage", "Historical spending patterns", "Regulatory preferences"]', 1, 'Risk-based prioritization combined with technology and automation delivers maximum compliance effectiveness per dollar invested.', 2);

-- Insert quiz questions for Integrating Compliance with Business Strategy
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Integrating Compliance with Business Strategy'), 'When should compliance be involved in strategic planning?', '["After decisions are made", "At the beginning of strategic planning", "Only for regulated industries", "When legal requires it"]', 1, 'Early compliance involvement in strategic planning ensures regulatory considerations inform rather than derail business initiatives.', 1),
((SELECT id FROM lessons WHERE title = 'Integrating Compliance with Business Strategy'), 'How should compliance be positioned strategically?', '["As cost center", "As business enabler and competitive advantage", "As necessary evil", "As legal function only"]', 1, 'Positioning compliance as a business enabler and potential competitive advantage drives integration and organizational support.', 2);

-- Insert quiz questions for Board Compliance Committee Effectiveness
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Board Compliance Committee Effectiveness'), 'What distinguishes an effective compliance committee?', '["Review of all compliance details", "Focus on strategic and material compliance issues", "Monthly multi-hour meetings", "Micromanagement of compliance staff"]', 1, 'Effective committees focus on strategic and material issues rather than operational details, enabling meaningful oversight without micromanaging.', 1),
((SELECT id FROM lessons WHERE title = 'Board Compliance Committee Effectiveness'), 'How should compliance committee expertise be ensured?', '["Any board member can serve", "Members with relevant regulatory and industry expertise", "Rotate all members annually", "Limit to financial experts only"]', 1, 'Committee members need relevant regulatory and industry expertise to provide informed oversight and valuable guidance to management.', 2);