-- Insert 7 Advanced AI Literacy lessons focused on Enterprise AI Governance and Strategy
INSERT INTO public.lessons (title, description, category, difficulty, duration_minutes, content, scenario_text, is_published, order_index) VALUES
('Enterprise AI Governance Frameworks', 'Establish comprehensive governance structures for responsible and effective AI deployment across your organization.', 'ai_literacy', 'advanced', 5, '{"sections": [{"title": "Governance Structure", "bullets": ["Define roles and responsibilities", "Establish AI oversight committees", "Create decision-making frameworks", "Set approval processes for AI initiatives"], "content": "Effective governance ensures AI aligns with organizational values and objectives."}, {"title": "Policy Components", "bullets": ["Ethics and responsible AI guidelines", "Data usage and privacy standards", "Risk assessment procedures", "Compliance and audit requirements"], "content": "Comprehensive policies provide guardrails for AI innovation."}]}', 'Your organization is deploying AI across multiple departments with no central oversight. How do you establish governance?', true, 37),

('AI Strategy and Roadmap Development', 'Create strategic AI roadmaps that align technology capabilities with business objectives and competitive advantage.', 'ai_literacy', 'advanced', 5, '{"sections": [{"title": "Strategic Assessment", "bullets": ["Identify high-impact use cases", "Assess organizational readiness", "Evaluate competitive landscape", "Define success metrics"], "content": "Strategy bridges AI capabilities with business value creation."}, {"title": "Roadmap Planning", "bullets": ["Prioritize initiatives by value and feasibility", "Plan for infrastructure and talent needs", "Create phased implementation timeline", "Build in learning and iteration cycles"], "content": "Roadmaps provide direction while maintaining flexibility."}]}', 'The board wants an AI strategy that delivers competitive advantage. How do you approach this?', true, 38),

('AI Risk Management at Enterprise Scale', 'Implement systematic risk management processes for AI systems deployed across large organizations.', 'ai_literacy', 'advanced', 5, '{"sections": [{"title": "Risk Categories", "bullets": ["Technical risks (bias, errors, security)", "Operational risks (reliability, integration)", "Regulatory and compliance risks", "Reputational and ethical risks"], "content": "Comprehensive risk identification prevents costly failures."}, {"title": "Mitigation Strategies", "bullets": ["Pre-deployment testing and validation", "Continuous monitoring and auditing", "Incident response procedures", "Regular risk reassessment"], "content": "Layered controls reduce AI-related risks across the enterprise."}]}', 'A customer-facing AI system made biased decisions that became public. How do you respond and prevent recurrence?', true, 39),

('AI Procurement and Vendor Management', 'Navigate the complex landscape of AI vendors and make informed procurement decisions for enterprise AI solutions.', 'ai_literacy', 'advanced', 5, '{"sections": [{"title": "Vendor Evaluation", "bullets": ["Assess technical capabilities and limitations", "Review data handling and security practices", "Evaluate vendor stability and support", "Understand total cost of ownership"], "content": "Due diligence prevents costly vendor lock-in and failures."}, {"title": "Contract Considerations", "bullets": ["Data ownership and usage rights", "Performance guarantees and SLAs", "Compliance and audit provisions", "Exit strategies and data portability"], "content": "Strong contracts protect organizational interests in AI partnerships."}]}', 'You need to select an AI vendor for a critical business function. What criteria guide your decision?', true, 40),

('Building AI Centers of Excellence', 'Establish centralized expertise hubs that accelerate AI adoption while maintaining quality and governance standards.', 'ai_literacy', 'advanced', 5, '{"sections": [{"title": "Center Structure", "bullets": ["Cross-functional team composition", "Centralized vs federated models", "Resource allocation and funding", "Collaboration with business units"], "content": "Centers of Excellence democratize AI while ensuring consistency."}, {"title": "Key Functions", "bullets": ["Standards and best practices development", "Training and capability building", "Tool and platform evaluation", "Project oversight and support"], "content": "COEs accelerate adoption while managing risks."}]}', 'AI projects across divisions are duplicating effort and creating inconsistencies. How do you establish a Center of Excellence?', true, 41),

('AI Policy and Regulatory Compliance', 'Navigate evolving AI regulations and develop policies that ensure compliance while enabling innovation.', 'ai_literacy', 'advanced', 5, '{"sections": [{"title": "Regulatory Landscape", "bullets": ["Industry-specific AI regulations", "Data protection and privacy laws", "Algorithmic accountability requirements", "International regulatory differences"], "content": "Proactive compliance prevents regulatory penalties and reputational damage."}, {"title": "Policy Implementation", "bullets": ["Translate regulations into operational policies", "Create compliance checkpoints in AI lifecycle", "Train teams on regulatory requirements", "Maintain documentation and audit trails"], "content": "Systematic compliance enables confident AI deployment."}]}', 'New AI regulations require algorithmic transparency. How do you ensure compliance across existing AI systems?', true, 42),

('AI Performance Monitoring and ROI Measurement', 'Implement systems to measure AI performance, business impact, and return on investment at enterprise scale.', 'ai_literacy', 'advanced', 5, '{"sections": [{"title": "Performance Metrics", "bullets": ["Technical performance indicators", "Business outcome measurements", "User satisfaction and adoption rates", "Cost and efficiency metrics"], "content": "What gets measured gets managed and improved."}, {"title": "ROI Framework", "bullets": ["Baseline performance documentation", "Direct and indirect benefit quantification", "Cost accounting (development, deployment, maintenance)", "Continuous value assessment"], "content": "Clear ROI justifies AI investments and guides optimization."}]}', 'Leadership questions whether AI investments are delivering value. How do you demonstrate and improve AI ROI?', true, 43);

-- Insert quiz questions for Enterprise AI Governance Frameworks
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Enterprise AI Governance Frameworks'), 'What is the primary purpose of AI governance?', '["Slow down AI adoption", "Align AI with organizational values and objectives", "Reduce AI spending", "Eliminate all AI risks"]', 1, 'Governance ensures AI initiatives align with organizational values and strategic objectives while managing risks appropriately.', 1),
((SELECT id FROM lessons WHERE title = 'Enterprise AI Governance Frameworks'), 'Who should be involved in AI governance oversight?', '["Only IT department", "Only legal and compliance", "Cross-functional stakeholders including business, legal, IT, and ethics", "External consultants only"]', 2, 'Effective AI governance requires diverse perspectives from business, legal, technical, and ethical domains to address all dimensions of AI deployment.', 2);

-- Insert quiz questions for AI Strategy and Roadmap Development
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'AI Strategy and Roadmap Development'), 'What should drive AI strategy prioritization?', '["Latest AI trends", "Business value and organizational readiness", "Competitor actions only", "Technology capabilities alone"]', 1, 'Successful AI strategy balances business value potential with organizational readiness to ensure initiatives deliver meaningful impact.', 1),
((SELECT id FROM lessons WHERE title = 'AI Strategy and Roadmap Development'), 'How should AI roadmaps handle uncertainty?', '["Commit to fixed 5-year plans", "Build in learning cycles and flexibility", "Avoid planning beyond next quarter", "Copy competitor roadmaps"]', 1, 'AI roadmaps should provide direction while incorporating learning cycles and flexibility to adapt as technology and understanding evolve.', 2);

-- Insert quiz questions for AI Risk Management at Enterprise Scale
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'AI Risk Management at Enterprise Scale'), 'What type of AI risk is most difficult to detect?', '["Technical errors", "Integration failures", "Subtle bias in decision-making", "Cost overruns"]', 2, 'Subtle bias in AI decision-making can be difficult to detect yet cause significant harm, requiring systematic monitoring and diverse testing.', 1),
((SELECT id FROM lessons WHERE title = 'AI Risk Management at Enterprise Scale'), 'When should AI risk assessment occur?', '["Only after deployment", "Only during development", "Continuously throughout AI lifecycle", "Only when incidents occur"]', 2, 'Continuous risk assessment throughout the AI lifecycle enables early detection and mitigation before issues become critical.', 2);

-- Insert quiz questions for AI Procurement and Vendor Management
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'AI Procurement and Vendor Management'), 'What is a critical AI vendor contract consideration?', '["Lowest price", "Data ownership and usage rights", "Vendor office location", "Number of features"]', 1, 'Data ownership and usage rights are critical because they determine control over your data and ability to switch vendors or use data elsewhere.', 1),
((SELECT id FROM lessons WHERE title = 'AI Procurement and Vendor Management'), 'How should you evaluate AI vendor claims?', '["Trust marketing materials", "Require proof of performance and test with your data", "Check social media reviews only", "Base decision on vendor size"]', 1, 'Vendor claims should be validated through proof of performance and testing with your actual data to ensure the solution meets your needs.', 2);

-- Insert quiz questions for Building AI Centers of Excellence
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Building AI Centers of Excellence'), 'What is a primary benefit of an AI Center of Excellence?', '["Centralized control over all AI decisions", "Accelerated adoption with consistent standards", "Reduced need for business unit involvement", "Elimination of all AI risks"]', 1, 'COEs accelerate AI adoption by providing expertise, standards, and support while maintaining quality and governance across the organization.', 1),
((SELECT id FROM lessons WHERE title = 'Building AI Centers of Excellence'), 'How should a COE balance centralization and business unit autonomy?', '["Full central control of all AI", "Enable business units with standards and support", "Complete business unit independence", "Rotate control quarterly"]', 1, 'Effective COEs provide standards, best practices, and support while enabling business units to innovate within appropriate guardrails.', 2);

-- Insert quiz questions for AI Policy and Regulatory Compliance
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'AI Policy and Regulatory Compliance'), 'How do you stay current with evolving AI regulations?', '["Wait for legal violations", "Proactive monitoring and policy updates", "Ignore until enforced", "Copy competitor policies"]', 1, 'Proactive monitoring of regulatory developments and regular policy updates ensure compliance before enforcement actions occur.', 1),
((SELECT id FROM lessons WHERE title = 'AI Policy and Regulatory Compliance'), 'What is essential for demonstrating AI compliance?', '["Verbal assurances", "Comprehensive documentation and audit trails", "Insurance policies", "External certifications only"]', 1, 'Comprehensive documentation and audit trails provide evidence of compliance and enable effective responses to regulatory inquiries.', 2);

-- Insert quiz questions for AI Performance Monitoring and ROI Measurement
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'AI Performance Monitoring and ROI Measurement'), 'What should AI performance metrics include?', '["Only technical accuracy", "Only cost savings", "Technical performance and business outcomes", "User satisfaction only"]', 2, 'Comprehensive metrics combine technical performance with business outcomes to provide a complete picture of AI value and effectiveness.', 1),
((SELECT id FROM lessons WHERE title = 'AI Performance Monitoring and ROI Measurement'), 'When should you measure AI ROI?', '["Only at project end", "Never, ROI is too complex", "Continuously from baseline through deployment", "Only when requested by finance"]', 2, 'Continuous ROI measurement from baseline establishment through deployment and operation enables ongoing optimization and value demonstration.', 2);