-- Insert 9 AI Literacy lessons
INSERT INTO public.lessons (title, description, category, difficulty, duration_minutes, content, scenario_text, is_published, order_index) VALUES
('AI Ethics and Responsible Use', 'Understand ethical considerations and responsible practices when working with AI systems in professional environments.', 'ai_literacy', 'intermediate', 5, '{"sections": [{"title": "Core Ethical Principles", "bullets": ["Transparency in AI decision-making", "Fairness and bias prevention", "Privacy and data protection", "Accountability for AI outcomes"], "content": "Ethical AI use requires understanding both capabilities and limitations."}, {"title": "Practical Guidelines", "bullets": ["Always verify AI-generated content", "Understand data sources and training", "Consider impact on stakeholders", "Document AI usage in critical decisions"], "content": "Apply ethical frameworks to daily AI interactions."}]}', 'Your team wants to use AI to screen job applications. What ethical considerations should guide this decision?', true, 19),

('Prompt Engineering Fundamentals', 'Master the art of crafting effective prompts to get better results from AI language models.', 'ai_literacy', 'beginner', 5, '{"sections": [{"title": "Prompt Structure", "bullets": ["Be specific and clear", "Provide context and examples", "Define desired format", "Iterate and refine"], "content": "Well-crafted prompts dramatically improve AI output quality."}, {"title": "Common Patterns", "bullets": ["Role-based prompts (act as...)", "Few-shot learning examples", "Chain-of-thought reasoning", "Constraint specification"], "content": "Use proven patterns to guide AI responses effectively."}]}', 'You need an AI to summarize a complex technical report for non-technical stakeholders.', true, 20),

('AI Tools for Productivity', 'Discover practical AI tools that can enhance your daily workflow and boost productivity.', 'ai_literacy', 'beginner', 5, '{"sections": [{"title": "Communication Tools", "bullets": ["Email drafting assistants", "Meeting transcription and summaries", "Language translation services", "Writing enhancement tools"], "content": "AI can streamline routine communication tasks."}, {"title": "Analysis Tools", "bullets": ["Data visualization assistants", "Pattern recognition tools", "Sentiment analysis", "Automated reporting"], "content": "Leverage AI for faster insights from complex data."}]}', 'Your team spends hours manually summarizing weekly meeting notes. How could AI help?', true, 21),

('Understanding AI Limitations', 'Learn to recognize when AI is not the right solution and understand its current constraints.', 'ai_literacy', 'intermediate', 5, '{"sections": [{"title": "Known Limitations", "bullets": ["Hallucinations and false information", "Lack of real-time knowledge", "Difficulty with nuanced context", "Bias from training data"], "content": "Critical thinking is essential when working with AI outputs."}, {"title": "When Not to Use AI", "bullets": ["High-stakes medical decisions", "Legal judgments", "Creative strategy requiring intuition", "Situations requiring empathy"], "content": "Human judgment remains irreplaceable in many domains."}]}', 'An AI suggests a controversial personnel decision. Should you implement it directly?', true, 22),

('AI in Decision Making', 'Explore how to effectively incorporate AI insights into your decision-making process.', 'ai_literacy', 'advanced', 5, '{"sections": [{"title": "AI as Decision Support", "bullets": ["Use AI for data analysis, not final decisions", "Combine AI insights with human judgment", "Validate recommendations against experience", "Maintain accountability for outcomes"], "content": "AI should augment, not replace, human decision-making."}, {"title": "Risk Assessment", "bullets": ["Evaluate confidence levels", "Consider edge cases", "Test assumptions", "Plan for AI failure modes"], "content": "Understand risks before acting on AI recommendations."}]}', 'AI analytics recommend downsizing a profitable division. How do you proceed?', true, 23),

('AI and Data Privacy', 'Understand privacy implications and best practices when using AI with sensitive data.', 'ai_literacy', 'advanced', 5, '{"sections": [{"title": "Privacy Risks", "bullets": ["Data leakage to training sets", "Unauthorized access through prompts", "Retention of sensitive information", "Third-party data sharing"], "content": "Protecting data privacy requires careful AI tool selection."}, {"title": "Protection Strategies", "bullets": ["Use enterprise AI with data controls", "Anonymize sensitive information", "Review privacy policies carefully", "Implement access controls"], "content": "Balance AI benefits with privacy protection."}]}', 'You want to use ChatGPT to analyze customer complaints containing personal information.', true, 24),

('Evaluating AI Output Quality', 'Develop skills to assess and validate AI-generated content for accuracy and reliability.', 'ai_literacy', 'intermediate', 5, '{"sections": [{"title": "Quality Indicators", "bullets": ["Consistency across multiple queries", "Alignment with known facts", "Logical coherence", "Source attribution when available"], "content": "Critical evaluation prevents propagation of AI errors."}, {"title": "Verification Methods", "bullets": ["Cross-reference with authoritative sources", "Test edge cases", "Seek second opinions", "Document assumptions"], "content": "Always verify before trusting AI output completely."}]}', 'An AI generates a financial forecast that seems too optimistic. How do you validate it?', true, 25),

('AI Collaboration Strategies', 'Learn effective patterns for working with AI as a collaborative tool in your workflow.', 'ai_literacy', 'intermediate', 5, '{"sections": [{"title": "Iterative Collaboration", "bullets": ["Start broad, then refine", "Provide feedback to improve results", "Break complex tasks into steps", "Save and reuse effective prompts"], "content": "Treat AI interaction as a conversation, not a single query."}, {"title": "Workflow Integration", "bullets": ["Identify repetitive tasks for AI", "Create templates and workflows", "Document successful patterns", "Share learnings with team"], "content": "Systematic AI integration multiplies productivity gains."}]}', 'Your team wants to standardize how everyone uses AI for report generation.', true, 26),

('Future of AI in the Workplace', 'Explore emerging AI trends and prepare for the evolving role of AI in professional settings.', 'ai_literacy', 'advanced', 5, '{"sections": [{"title": "Emerging Capabilities", "bullets": ["Multimodal AI (text, image, video)", "Autonomous agents and assistants", "Real-time collaboration tools", "Domain-specific AI models"], "content": "AI capabilities continue to expand rapidly."}, {"title": "Preparing for Change", "bullets": ["Focus on uniquely human skills", "Stay informed about AI developments", "Experiment with new tools", "Develop AI literacy across teams"], "content": "Adapt proactively to maintain competitive advantage."}]}', 'Your industry is seeing rapid AI adoption. How do you position your team for success?', true, 27);

-- Insert quiz questions for AI Ethics and Responsible Use
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'AI Ethics and Responsible Use'), 'What is a key ethical principle when using AI for hiring decisions?', '["Maximize speed of decisions", "Ensure transparency and fairness", "Minimize human involvement", "Prioritize cost reduction"]', 1, 'Transparency and fairness are fundamental to ethical AI use, especially in high-impact decisions like hiring that affect people''s livelihoods.', 1),
((SELECT id FROM lessons WHERE title = 'AI Ethics and Responsible Use'), 'When should you document AI usage in decision-making?', '["Only for legal compliance", "Never, to protect IP", "In critical decisions affecting people", "Only when AI makes errors"]', 2, 'Critical decisions that impact stakeholders should document AI involvement to maintain accountability and enable auditing.', 2);

-- Insert quiz questions for Prompt Engineering Fundamentals
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Prompt Engineering Fundamentals'), 'What makes a prompt more effective?', '["Being vague to allow creativity", "Providing specific context and examples", "Using technical jargon", "Keeping it as short as possible"]', 1, 'Specific context and examples help the AI understand exactly what you need, leading to better, more relevant outputs.', 1),
((SELECT id FROM lessons WHERE title = 'Prompt Engineering Fundamentals'), 'What is "few-shot learning" in prompt engineering?', '["Using very short prompts", "Providing examples in your prompt", "Limiting AI responses", "Using multiple AI tools"]', 1, 'Few-shot learning involves providing examples in your prompt to demonstrate the pattern or format you want the AI to follow.', 2);

-- Insert quiz questions for AI Tools for Productivity
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'AI Tools for Productivity'), 'Which task is most suitable for AI automation?', '["Strategic planning", "Meeting transcription", "Building client relationships", "Making ethical judgments"]', 1, 'Meeting transcription is a routine, time-consuming task that AI can handle effectively, freeing humans for higher-value work.', 1),
((SELECT id FROM lessons WHERE title = 'AI Tools for Productivity'), 'How should you approach implementing AI productivity tools?', '["Replace all manual processes immediately", "Start with repetitive, time-consuming tasks", "Only use in non-critical areas", "Avoid due to security risks"]', 1, 'Starting with repetitive, time-consuming tasks allows you to gain value quickly while learning to use AI tools effectively.', 2);

-- Insert quiz questions for Understanding AI Limitations
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Understanding AI Limitations'), 'What is an "AI hallucination"?', '["AI refusing to respond", "AI generating false information confidently", "AI being too creative", "AI working too slowly"]', 1, 'AI hallucinations occur when models generate false or fabricated information while presenting it as factual, requiring human verification.', 1),
((SELECT id FROM lessons WHERE title = 'Understanding AI Limitations'), 'When is AI least appropriate to use?', '["Data analysis", "Draft email writing", "High-stakes medical diagnoses", "Meeting summaries"]', 2, 'High-stakes medical diagnoses require specialized human expertise, empathy, and accountability that AI cannot provide.', 2);

-- Insert quiz questions for AI in Decision Making
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'AI in Decision Making'), 'How should AI recommendations be used in decision-making?', '["Implement them directly", "As one input among many", "Only when they agree with intuition", "Ignore them to avoid bias"]', 1, 'AI should provide data-driven insights as one input, combined with human judgment, experience, and contextual understanding.', 1),
((SELECT id FROM lessons WHERE title = 'AI in Decision Making'), 'What should you do before acting on AI recommendations?', '["Get stakeholder approval", "Validate assumptions and test edge cases", "Implement immediately for speed", "Get legal clearance"]', 1, 'Testing assumptions and edge cases helps identify potential failures before AI recommendations impact real outcomes.', 2);

-- Insert quiz questions for AI and Data Privacy
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'AI and Data Privacy'), 'What is a key privacy risk when using public AI tools?', '["Slow processing", "High cost", "Data leakage to training sets", "Limited features"]', 2, 'Public AI tools may use your inputs for training, potentially exposing sensitive information to others or the model itself.', 1),
((SELECT id FROM lessons WHERE title = 'AI and Data Privacy'), 'How should you handle sensitive data with AI?', '["Never use AI with sensitive data", "Anonymize before processing", "Only use during business hours", "Get written consent first"]', 1, 'Anonymizing sensitive information before AI processing protects privacy while still allowing you to benefit from AI capabilities.', 2);

-- Insert quiz questions for Evaluating AI Output Quality
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Evaluating AI Output Quality'), 'How do you verify AI-generated content?', '["Trust it if it sounds confident", "Cross-reference with authoritative sources", "Use multiple AI tools", "Check grammar and spelling"]', 1, 'Cross-referencing with authoritative sources is the most reliable way to validate AI output accuracy.', 1),
((SELECT id FROM lessons WHERE title = 'Evaluating AI Output Quality'), 'What indicates potential AI output problems?', '["Technical terminology", "Inconsistency across similar queries", "Detailed responses", "Fast generation"]', 1, 'Inconsistent responses to similar queries suggest the AI may be unreliable or hallucinating information.', 2);

-- Insert quiz questions for AI Collaboration Strategies
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'AI Collaboration Strategies'), 'What is an effective AI collaboration approach?', '["Give one detailed prompt and accept the result", "Iterate with feedback to refine results", "Use the same prompt for everything", "Never revise AI output"]', 1, 'Iterative feedback helps the AI understand your needs better and produces higher quality results over time.', 1),
((SELECT id FROM lessons WHERE title = 'AI Collaboration Strategies'), 'How should teams standardize AI use?', '["Everyone uses different tools", "Document and share effective patterns", "Restrict AI to one person", "Avoid documentation"]', 1, 'Documenting and sharing successful patterns helps the entire team benefit from AI more effectively and consistently.', 2);

-- Insert quiz questions for Future of AI in the Workplace
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Future of AI in the Workplace'), 'What skills become more valuable as AI advances?', '["Routine data entry", "Creative problem-solving", "Memorization", "Following scripts exactly"]', 1, 'Creative problem-solving, empathy, and strategic thinking are uniquely human skills that complement rather than compete with AI.', 1),
((SELECT id FROM lessons WHERE title = 'Future of AI in the Workplace'), 'How should professionals prepare for AI evolution?', '["Resist adoption", "Develop AI literacy continuously", "Focus only on current tools", "Avoid experimentation"]', 1, 'Continuous learning and experimentation with AI tools keeps professionals competitive and adaptable as capabilities evolve.', 2);

-- Insert 9 Compliance Workflows lessons
INSERT INTO public.lessons (title, description, category, difficulty, duration_minutes, content, scenario_text, is_published, order_index) VALUES
('Understanding Regulatory Frameworks', 'Learn the fundamentals of regulatory compliance and how frameworks apply to your industry.', 'compliance_workflows', 'beginner', 5, '{"sections": [{"title": "Core Compliance Concepts", "bullets": ["Know your industry regulations", "Understand enforcement mechanisms", "Identify compliance obligations", "Map regulations to business processes"], "content": "Effective compliance starts with understanding applicable regulations."}, {"title": "Framework Structure", "bullets": ["Federal vs state requirements", "Industry-specific regulations", "International standards", "Internal policies vs external mandates"], "content": "Different frameworks require different approaches and priorities."}]}', 'Your company is expanding into a new state with different regulations. How do you ensure compliance?', true, 28),

('Risk Assessment in Compliance', 'Master techniques for identifying and evaluating compliance risks in your organization.', 'compliance_workflows', 'intermediate', 5, '{"sections": [{"title": "Risk Identification", "bullets": ["Map business processes to regulations", "Identify potential violation points", "Assess likelihood and impact", "Prioritize high-risk areas"], "content": "Systematic risk assessment prevents compliance failures."}, {"title": "Mitigation Strategies", "bullets": ["Implement controls and monitoring", "Create contingency plans", "Document risk decisions", "Regular risk reassessment"], "content": "Proactive risk management reduces compliance incidents."}]}', 'A new product feature may violate data privacy regulations. How do you assess and address this risk?', true, 29),

('Compliance Training Programs', 'Design and implement effective compliance training that drives behavioral change.', 'compliance_workflows', 'intermediate', 5, '{"sections": [{"title": "Training Essentials", "bullets": ["Role-specific content", "Regular refresher courses", "Real-world scenarios", "Assessment and certification"], "content": "Effective training makes compliance part of organizational culture."}, {"title": "Engagement Strategies", "bullets": ["Interactive learning methods", "Leadership participation", "Consequences for non-completion", "Track and measure effectiveness"], "content": "Engaged employees are compliant employees."}]}', 'Compliance training completion rates are low and violations are increasing. What do you do?', true, 30),

('Audit Preparation and Response', 'Prepare for compliance audits and respond effectively to audit findings.', 'compliance_workflows', 'advanced', 5, '{"sections": [{"title": "Audit Readiness", "bullets": ["Maintain organized documentation", "Conduct internal pre-audits", "Designate audit coordinators", "Prepare supporting evidence"], "content": "Preparation minimizes audit stress and negative findings."}, {"title": "Response Management", "bullets": ["Address findings promptly", "Develop corrective action plans", "Track remediation progress", "Learn from audit feedback"], "content": "How you respond to audits matters as much as initial compliance."}]}', 'Auditors have identified deficiencies in your compliance program. How do you respond?', true, 31),

('Data Protection and Privacy', 'Implement robust data protection practices to meet privacy regulations and build trust.', 'compliance_workflows', 'advanced', 5, '{"sections": [{"title": "Privacy Principles", "bullets": ["Data minimization", "Purpose limitation", "Transparency in data use", "Individual rights and consent"], "content": "Privacy regulations require respecting individual data rights."}, {"title": "Implementation Tactics", "bullets": ["Privacy by design", "Data mapping and inventory", "Access controls and encryption", "Breach response planning"], "content": "Technical and organizational measures protect personal data."}]}', 'A customer requests deletion of all their personal data. How do you comply while maintaining necessary records?', true, 32),

('Third-Party Vendor Compliance', 'Manage compliance risks from third-party vendors and service providers.', 'compliance_workflows', 'intermediate', 5, '{"sections": [{"title": "Vendor Assessment", "bullets": ["Due diligence before engagement", "Review security and compliance certifications", "Assess regulatory alignment", "Contractual compliance obligations"], "content": "You remain responsible for vendor compliance."}, {"title": "Ongoing Monitoring", "bullets": ["Regular vendor audits", "Performance metrics tracking", "Incident reporting requirements", "Contract review and updates"], "content": "Continuous oversight ensures vendor compliance."}]}', 'A key vendor had a data breach affecting your customers. What are your compliance obligations?', true, 33),

('Incident Response and Reporting', 'Develop procedures for responding to and reporting compliance incidents.', 'compliance_workflows', 'advanced', 5, '{"sections": [{"title": "Incident Detection", "bullets": ["Monitoring and alert systems", "Employee reporting channels", "Automated compliance checks", "Regular system reviews"], "content": "Early detection minimizes incident impact."}, {"title": "Response Protocol", "bullets": ["Immediate containment actions", "Investigation and root cause analysis", "Regulatory notification requirements", "Remediation and prevention"], "content": "Swift, systematic response is critical for compliance."}]}', 'You discover employees have been accessing customer data without authorization. What steps do you take?', true, 34),

('Compliance Metrics and Reporting', 'Implement effective metrics to measure and communicate compliance program effectiveness.', 'compliance_workflows', 'intermediate', 5, '{"sections": [{"title": "Key Metrics", "bullets": ["Training completion rates", "Incident frequency and severity", "Audit findings trends", "Control effectiveness measures"], "content": "Measuring compliance enables continuous improvement."}, {"title": "Executive Reporting", "bullets": ["Clear, concise dashboards", "Focus on material risks", "Actionable recommendations", "Trend analysis over time"], "content": "Effective reporting ensures leadership awareness and support."}]}', 'The board wants to know how effective your compliance program is. How do you demonstrate value?', true, 35),

('Building a Compliance Culture', 'Foster an organizational culture where compliance is valued and practiced by everyone.', 'compliance_workflows', 'advanced', 5, '{"sections": [{"title": "Culture Foundation", "bullets": ["Tone from the top", "Clear values and expectations", "Recognition and consequences", "Open communication channels"], "content": "Culture determines whether policies translate to practice."}, {"title": "Sustaining Momentum", "bullets": ["Regular communication campaigns", "Celebrate compliance wins", "Integrate into performance reviews", "Make compliance easy to do right"], "content": "Long-term success requires ongoing cultural reinforcement."}]}', 'Despite clear policies, employees regularly take compliance shortcuts. How do you change this?', true, 36);

-- Insert quiz questions for Understanding Regulatory Frameworks
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Understanding Regulatory Frameworks'), 'What is the first step in compliance?', '["Hiring lawyers", "Understanding applicable regulations", "Creating policies", "Training employees"]', 1, 'Understanding which regulations apply to your business is the foundation for all other compliance activities.', 1),
((SELECT id FROM lessons WHERE title = 'Understanding Regulatory Frameworks'), 'How do federal and state regulations interact?', '["State always supersedes federal", "Federal always supersedes state", "Stricter standard typically applies", "They never overlap"]', 2, 'Generally, the stricter standard applies whether federal or state, and organizations must comply with both.', 2);

-- Insert quiz questions for Risk Assessment in Compliance
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Risk Assessment in Compliance'), 'What factors determine compliance risk priority?', '["Only likelihood of occurrence", "Only potential impact", "Likelihood and impact combined", "Regulatory preference"]', 2, 'Effective risk assessment considers both the likelihood of violations and their potential impact to prioritize appropriately.', 1),
((SELECT id FROM lessons WHERE title = 'Risk Assessment in Compliance'), 'How often should risk assessments be conducted?', '["Once at startup", "Only after incidents", "Regularly and after changes", "When auditors request"]', 2, 'Regular reassessment and evaluation after significant changes ensures risk management stays current.', 2);

-- Insert quiz questions for Compliance Training Programs
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Compliance Training Programs'), 'What makes compliance training most effective?', '["Annual long presentations", "Role-specific interactive scenarios", "Legal document reading", "Email reminders only"]', 1, 'Role-specific interactive training that uses real scenarios is most effective at driving behavioral change.', 1),
((SELECT id FROM lessons WHERE title = 'Compliance Training Programs'), 'How do you measure training effectiveness?', '["Completion rates only", "Quiz scores only", "Behavior change and incident reduction", "Employee feedback only"]', 2, 'True effectiveness is measured by actual behavior change and reduction in compliance incidents.', 2);

-- Insert quiz questions for Audit Preparation and Response
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Audit Preparation and Response'), 'What is most important for audit readiness?', '["Expensive consultants", "Organized documentation", "Delaying the audit", "Minimal preparation"]', 1, 'Well-organized documentation demonstrating compliance activities is the foundation of successful audits.', 1),
((SELECT id FROM lessons WHERE title = 'Audit Preparation and Response'), 'How should you respond to audit findings?', '["Dispute everything", "Develop prompt corrective actions", "Ignore minor findings", "Wait for formal requirements"]', 1, 'Prompt development of corrective action plans demonstrates commitment to compliance and often reduces penalties.', 2);

-- Insert quiz questions for Data Protection and Privacy
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Data Protection and Privacy'), 'What is the principle of data minimization?', '["Minimize storage costs", "Collect only necessary data", "Reduce employee access", "Minimize compliance effort"]', 1, 'Data minimization means collecting and retaining only data that is necessary for specified purposes.', 1),
((SELECT id FROM lessons WHERE title = 'Data Protection and Privacy'), 'What is privacy by design?', '["Designing secure facilities", "Building privacy into systems from start", "Graphic design for privacy policies", "Restricting design access"]', 1, 'Privacy by design means building privacy protection into systems and processes from the beginning, not adding it later.', 2);

-- Insert quiz questions for Third-Party Vendor Compliance
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Third-Party Vendor Compliance'), 'What is your compliance responsibility for vendors?', '["None, vendors are independent", "You remain ultimately responsible", "Only for contracted services", "Responsibility transfers to vendor"]', 1, 'Organizations remain responsible for vendor compliance with regulations, even when outsourcing services.', 1),
((SELECT id FROM lessons WHERE title = 'Third-Party Vendor Compliance'), 'When should vendor compliance be assessed?', '["Only after problems occur", "Before engagement and ongoing", "Annual reviews only", "When contracts renew"]', 1, 'Due diligence before engagement and ongoing monitoring throughout the relationship ensures continuous vendor compliance.', 2);

-- Insert quiz questions for Incident Response and Reporting
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Incident Response and Reporting'), 'What is the first priority in incident response?', '["Determine blame", "Containment and mitigation", "Public relations", "Legal consultation"]', 1, 'Immediate containment prevents further harm and is always the first priority in incident response.', 1),
((SELECT id FROM lessons WHERE title = 'Incident Response and Reporting'), 'When must compliance incidents be reported?', '["Never, to protect reputation", "As required by applicable regulations", "Only if discovered by auditors", "At year-end reviews"]', 1, 'Regulations often specify strict timeframes for incident reporting, and failure to report can increase penalties.', 2);

-- Insert quiz questions for Compliance Metrics and Reporting
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Compliance Metrics and Reporting'), 'What makes compliance metrics valuable?', '["Complex statistical analysis", "Actionable insights for improvement", "Volume of data collected", "Impressive visualizations"]', 1, 'Valuable metrics provide actionable insights that enable continuous improvement of compliance programs.', 1),
((SELECT id FROM lessons WHERE title = 'Compliance Metrics and Reporting'), 'How should compliance be reported to executives?', '["Detailed technical analysis", "Legal jargon and citations", "Clear dashboards focused on material risks", "Only when problems occur"]', 2, 'Executive reporting should be clear, concise, and focused on material risks and actionable information.', 2);

-- Insert quiz questions for Building a Compliance Culture
INSERT INTO public.quiz_questions (lesson_id, question_text, options, correct_answer, explanation, order_index) VALUES
((SELECT id FROM lessons WHERE title = 'Building a Compliance Culture'), 'What is most critical for compliance culture?', '["Strict policies", "Tone from leadership", "Punishment for violations", "Complex procedures"]', 1, 'Leadership tone and example are the most powerful drivers of organizational compliance culture.', 1),
((SELECT id FROM lessons WHERE title = 'Building a Compliance Culture'), 'How do you sustain compliance culture long-term?', '["Annual training only", "Integrate into daily operations and recognition", "Fear of punishment", "Quarterly memos"]', 1, 'Sustainable compliance culture requires integration into daily operations, performance management, and positive recognition.', 2);